/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as EnvironmentsEnvIdRouteImport } from './routes/environments.$envId'
import { Route as DashboardWorkspacesRouteImport } from './routes/dashboard.workspaces'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardTeamsRouteImport } from './routes/dashboard.teams'
import { Route as DashboardServicesRouteImport } from './routes/dashboard.services'
import { Route as DashboardRolesRouteImport } from './routes/dashboard.roles'
import { Route as DashboardRegistriesRouteImport } from './routes/dashboard.registries'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardNoAccessRouteImport } from './routes/dashboard.no-access'
import { Route as DashboardEnvironmentsRouteImport } from './routes/dashboard.environments'
import { Route as DashboardDeploymentsRouteImport } from './routes/dashboard.deployments'
import { Route as DashboardDeploymentControlsRouteImport } from './routes/dashboard.deployment-controls'
import { Route as DashboardDepartmentsRouteImport } from './routes/dashboard.departments'
import { Route as DashboardAccessRequestsRouteImport } from './routes/dashboard.access-requests'
import { Route as DashboardEnvironmentsIndexRouteImport } from './routes/dashboard.environments.index'
import { Route as EnvironmentsEnvIdIntegrationsRouteImport } from './routes/environments.$envId.integrations'
import { Route as DashboardEnvironmentsEnvIdRouteImport } from './routes/dashboard.environments.$envId'
import { Route as DashboardEnvironmentsEnvIdIndexRouteImport } from './routes/dashboard.environments.$envId.index'
import { Route as DashboardEnvironmentsEnvIdSettingsRouteImport } from './routes/dashboard.environments.$envId.settings'
import { Route as DashboardEnvironmentsEnvIdServicesRouteImport } from './routes/dashboard.environments.$envId.services'
import { Route as DashboardEnvironmentsEnvIdServiceCatalogRouteImport } from './routes/dashboard.environments.$envId.service-catalog'
import { Route as DashboardEnvironmentsEnvIdSecretsRouteImport } from './routes/dashboard.environments.$envId.secrets'
import { Route as DashboardEnvironmentsEnvIdRuntimeEventsRouteImport } from './routes/dashboard.environments.$envId.runtime-events'
import { Route as DashboardEnvironmentsEnvIdRegistriesRouteImport } from './routes/dashboard.environments.$envId.registries'
import { Route as DashboardEnvironmentsEnvIdPoliciesRouteImport } from './routes/dashboard.environments.$envId.policies'
import { Route as DashboardEnvironmentsEnvIdPodsRouteImport } from './routes/dashboard.environments.$envId.pods'
import { Route as DashboardEnvironmentsEnvIdPlatformRouteImport } from './routes/dashboard.environments.$envId.platform'
import { Route as DashboardEnvironmentsEnvIdMetricsRouteImport } from './routes/dashboard.environments.$envId.metrics'
import { Route as DashboardEnvironmentsEnvIdLogsRouteImport } from './routes/dashboard.environments.$envId.logs'
import { Route as DashboardEnvironmentsEnvIdIntegrationsRouteImport } from './routes/dashboard.environments.$envId.integrations'
import { Route as DashboardEnvironmentsEnvIdDeploymentsRouteImport } from './routes/dashboard.environments.$envId.deployments'
import { Route as DashboardEnvironmentsEnvIdContainersRouteImport } from './routes/dashboard.environments.$envId.containers'
import { Route as DashboardEnvironmentsEnvIdServicesIndexRouteImport } from './routes/dashboard.environments.$envId.services.index'
import { Route as DashboardEnvironmentsEnvIdPodsIndexRouteImport } from './routes/dashboard.environments.$envId.pods.index'
import { Route as DashboardEnvironmentsEnvIdDeploymentsIndexRouteImport } from './routes/dashboard.environments.$envId.deployments.index'
import { Route as DashboardEnvironmentsEnvIdPlatformStorageRouteImport } from './routes/dashboard.environments.$envId.platform.storage'
import { Route as DashboardEnvironmentsEnvIdPlatformSecretsRouteImport } from './routes/dashboard.environments.$envId.platform.secrets'
import { Route as DashboardEnvironmentsEnvIdPlatformRuntimeRouteImport } from './routes/dashboard.environments.$envId.platform.runtime'
import { Route as DashboardEnvironmentsEnvIdPlatformNetworkingRouteImport } from './routes/dashboard.environments.$envId.platform.networking'
import { Route as DashboardEnvironmentsEnvIdPlatformLogsRouteImport } from './routes/dashboard.environments.$envId.platform.logs'
import { Route as DashboardEnvironmentsEnvIdDeploymentsJobIdRouteImport } from './routes/dashboard.environments.$envId.deployments.$jobId'
import { Route as DashboardEnvironmentsEnvIdPodsNamespaceNameRouteImport } from './routes/dashboard.environments.$envId.pods.$namespace.$name'
import { Route as DashboardEnvironmentsEnvIdServicesK8sNamespaceNameRouteImport } from './routes/dashboard.environments.$envId.services.k8s.$namespace.$name'
import { Route as DashboardEnvironmentsEnvIdDeploymentsK8sNamespaceNameRouteImport } from './routes/dashboard.environments.$envId.deployments.k8s.$namespace.$name'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const EnvironmentsEnvIdRoute = EnvironmentsEnvIdRouteImport.update({
  id: '/environments/$envId',
  path: '/environments/$envId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkspacesRoute = DashboardWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamsRoute = DashboardTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServicesRoute = DashboardServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRolesRoute = DashboardRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRegistriesRoute = DashboardRegistriesRouteImport.update({
  id: '/registries',
  path: '/registries',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNoAccessRoute = DashboardNoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEnvironmentsRoute = DashboardEnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeploymentsRoute = DashboardDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeploymentControlsRoute =
  DashboardDeploymentControlsRouteImport.update({
    id: '/deployment-controls',
    path: '/deployment-controls',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDepartmentsRoute = DashboardDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccessRequestsRoute = DashboardAccessRequestsRouteImport.update({
  id: '/access-requests',
  path: '/access-requests',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEnvironmentsIndexRoute =
  DashboardEnvironmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardEnvironmentsRoute,
  } as any)
const EnvironmentsEnvIdIntegrationsRoute =
  EnvironmentsEnvIdIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => EnvironmentsEnvIdRoute,
  } as any)
const DashboardEnvironmentsEnvIdRoute =
  DashboardEnvironmentsEnvIdRouteImport.update({
    id: '/$envId',
    path: '/$envId',
    getParentRoute: () => DashboardEnvironmentsRoute,
  } as any)
const DashboardEnvironmentsEnvIdIndexRoute =
  DashboardEnvironmentsEnvIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardEnvironmentsEnvIdRoute,
  } as any)
const DashboardEnvironmentsEnvIdSettingsRoute =
  DashboardEnvironmentsEnvIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardEnvironmentsEnvIdRoute,
  } as any)
const DashboardEnvironmentsEnvIdServicesRoute =
  DashboardEnvironmentsEnvIdServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => DashboardEnvironmentsEnvIdRoute,
  } as any)
const DashboardEnvironmentsEnvIdServiceCatalogRoute =
  DashboardEnvironmentsEnvIdServiceCatalogRouteImport.update({
    id: '/service-catalog',
    path: '/service-catalog',
    getParentRoute: () => DashboardEnvironmentsEnvIdRoute,
  } as any)
const DashboardEnvironmentsEnvIdSecretsRoute =
  DashboardEnvironmentsEnvIdSecretsRouteImport.update({
    id: '/secrets',
    path: '/secrets',
    getParentRoute: () => DashboardEnvironmentsEnvIdRoute,
  } as any)
const DashboardEnvironmentsEnvIdRuntimeEventsRoute =
  DashboardEnvironmentsEnvIdRuntimeEventsRouteImport.update({
    id: '/runtime-events',
    path: '/runtime-events',
    getParentRoute: () => DashboardEnvironmentsEnvIdRoute,
  } as any)
const DashboardEnvironmentsEnvIdRegistriesRoute =
  DashboardEnvironmentsEnvIdRegistriesRouteImport.update({
    id: '/registries',
    path: '/registries',
    getParentRoute: () => DashboardEnvironmentsEnvIdRoute,
  } as any)
const DashboardEnvironmentsEnvIdPoliciesRoute =
  DashboardEnvironmentsEnvIdPoliciesRouteImport.update({
    id: '/policies',
    path: '/policies',
    getParentRoute: () => DashboardEnvironmentsEnvIdRoute,
  } as any)
const DashboardEnvironmentsEnvIdPodsRoute =
  DashboardEnvironmentsEnvIdPodsRouteImport.update({
    id: '/pods',
    path: '/pods',
    getParentRoute: () => DashboardEnvironmentsEnvIdRoute,
  } as any)
const DashboardEnvironmentsEnvIdPlatformRoute =
  DashboardEnvironmentsEnvIdPlatformRouteImport.update({
    id: '/platform',
    path: '/platform',
    getParentRoute: () => DashboardEnvironmentsEnvIdRoute,
  } as any)
const DashboardEnvironmentsEnvIdMetricsRoute =
  DashboardEnvironmentsEnvIdMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => DashboardEnvironmentsEnvIdRoute,
  } as any)
const DashboardEnvironmentsEnvIdLogsRoute =
  DashboardEnvironmentsEnvIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => DashboardEnvironmentsEnvIdRoute,
  } as any)
const DashboardEnvironmentsEnvIdIntegrationsRoute =
  DashboardEnvironmentsEnvIdIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => DashboardEnvironmentsEnvIdRoute,
  } as any)
const DashboardEnvironmentsEnvIdDeploymentsRoute =
  DashboardEnvironmentsEnvIdDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => DashboardEnvironmentsEnvIdRoute,
  } as any)
const DashboardEnvironmentsEnvIdContainersRoute =
  DashboardEnvironmentsEnvIdContainersRouteImport.update({
    id: '/containers',
    path: '/containers',
    getParentRoute: () => DashboardEnvironmentsEnvIdRoute,
  } as any)
const DashboardEnvironmentsEnvIdServicesIndexRoute =
  DashboardEnvironmentsEnvIdServicesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardEnvironmentsEnvIdServicesRoute,
  } as any)
const DashboardEnvironmentsEnvIdPodsIndexRoute =
  DashboardEnvironmentsEnvIdPodsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardEnvironmentsEnvIdPodsRoute,
  } as any)
const DashboardEnvironmentsEnvIdDeploymentsIndexRoute =
  DashboardEnvironmentsEnvIdDeploymentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardEnvironmentsEnvIdDeploymentsRoute,
  } as any)
const DashboardEnvironmentsEnvIdPlatformStorageRoute =
  DashboardEnvironmentsEnvIdPlatformStorageRouteImport.update({
    id: '/storage',
    path: '/storage',
    getParentRoute: () => DashboardEnvironmentsEnvIdPlatformRoute,
  } as any)
const DashboardEnvironmentsEnvIdPlatformSecretsRoute =
  DashboardEnvironmentsEnvIdPlatformSecretsRouteImport.update({
    id: '/secrets',
    path: '/secrets',
    getParentRoute: () => DashboardEnvironmentsEnvIdPlatformRoute,
  } as any)
const DashboardEnvironmentsEnvIdPlatformRuntimeRoute =
  DashboardEnvironmentsEnvIdPlatformRuntimeRouteImport.update({
    id: '/runtime',
    path: '/runtime',
    getParentRoute: () => DashboardEnvironmentsEnvIdPlatformRoute,
  } as any)
const DashboardEnvironmentsEnvIdPlatformNetworkingRoute =
  DashboardEnvironmentsEnvIdPlatformNetworkingRouteImport.update({
    id: '/networking',
    path: '/networking',
    getParentRoute: () => DashboardEnvironmentsEnvIdPlatformRoute,
  } as any)
const DashboardEnvironmentsEnvIdPlatformLogsRoute =
  DashboardEnvironmentsEnvIdPlatformLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => DashboardEnvironmentsEnvIdPlatformRoute,
  } as any)
const DashboardEnvironmentsEnvIdDeploymentsJobIdRoute =
  DashboardEnvironmentsEnvIdDeploymentsJobIdRouteImport.update({
    id: '/$jobId',
    path: '/$jobId',
    getParentRoute: () => DashboardEnvironmentsEnvIdDeploymentsRoute,
  } as any)
const DashboardEnvironmentsEnvIdPodsNamespaceNameRoute =
  DashboardEnvironmentsEnvIdPodsNamespaceNameRouteImport.update({
    id: '/$namespace/$name',
    path: '/$namespace/$name',
    getParentRoute: () => DashboardEnvironmentsEnvIdPodsRoute,
  } as any)
const DashboardEnvironmentsEnvIdServicesK8sNamespaceNameRoute =
  DashboardEnvironmentsEnvIdServicesK8sNamespaceNameRouteImport.update({
    id: '/k8s/$namespace/$name',
    path: '/k8s/$namespace/$name',
    getParentRoute: () => DashboardEnvironmentsEnvIdServicesRoute,
  } as any)
const DashboardEnvironmentsEnvIdDeploymentsK8sNamespaceNameRoute =
  DashboardEnvironmentsEnvIdDeploymentsK8sNamespaceNameRouteImport.update({
    id: '/k8s/$namespace/$name',
    path: '/k8s/$namespace/$name',
    getParentRoute: () => DashboardEnvironmentsEnvIdDeploymentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/access-requests': typeof DashboardAccessRequestsRoute
  '/dashboard/departments': typeof DashboardDepartmentsRoute
  '/dashboard/deployment-controls': typeof DashboardDeploymentControlsRoute
  '/dashboard/deployments': typeof DashboardDeploymentsRoute
  '/dashboard/environments': typeof DashboardEnvironmentsRouteWithChildren
  '/dashboard/no-access': typeof DashboardNoAccessRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/registries': typeof DashboardRegistriesRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/workspaces': typeof DashboardWorkspacesRoute
  '/environments/$envId': typeof EnvironmentsEnvIdRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/environments/$envId': typeof DashboardEnvironmentsEnvIdRouteWithChildren
  '/environments/$envId/integrations': typeof EnvironmentsEnvIdIntegrationsRoute
  '/dashboard/environments/': typeof DashboardEnvironmentsIndexRoute
  '/dashboard/environments/$envId/containers': typeof DashboardEnvironmentsEnvIdContainersRoute
  '/dashboard/environments/$envId/deployments': typeof DashboardEnvironmentsEnvIdDeploymentsRouteWithChildren
  '/dashboard/environments/$envId/integrations': typeof DashboardEnvironmentsEnvIdIntegrationsRoute
  '/dashboard/environments/$envId/logs': typeof DashboardEnvironmentsEnvIdLogsRoute
  '/dashboard/environments/$envId/metrics': typeof DashboardEnvironmentsEnvIdMetricsRoute
  '/dashboard/environments/$envId/platform': typeof DashboardEnvironmentsEnvIdPlatformRouteWithChildren
  '/dashboard/environments/$envId/pods': typeof DashboardEnvironmentsEnvIdPodsRouteWithChildren
  '/dashboard/environments/$envId/policies': typeof DashboardEnvironmentsEnvIdPoliciesRoute
  '/dashboard/environments/$envId/registries': typeof DashboardEnvironmentsEnvIdRegistriesRoute
  '/dashboard/environments/$envId/runtime-events': typeof DashboardEnvironmentsEnvIdRuntimeEventsRoute
  '/dashboard/environments/$envId/secrets': typeof DashboardEnvironmentsEnvIdSecretsRoute
  '/dashboard/environments/$envId/service-catalog': typeof DashboardEnvironmentsEnvIdServiceCatalogRoute
  '/dashboard/environments/$envId/services': typeof DashboardEnvironmentsEnvIdServicesRouteWithChildren
  '/dashboard/environments/$envId/settings': typeof DashboardEnvironmentsEnvIdSettingsRoute
  '/dashboard/environments/$envId/': typeof DashboardEnvironmentsEnvIdIndexRoute
  '/dashboard/environments/$envId/deployments/$jobId': typeof DashboardEnvironmentsEnvIdDeploymentsJobIdRoute
  '/dashboard/environments/$envId/platform/logs': typeof DashboardEnvironmentsEnvIdPlatformLogsRoute
  '/dashboard/environments/$envId/platform/networking': typeof DashboardEnvironmentsEnvIdPlatformNetworkingRoute
  '/dashboard/environments/$envId/platform/runtime': typeof DashboardEnvironmentsEnvIdPlatformRuntimeRoute
  '/dashboard/environments/$envId/platform/secrets': typeof DashboardEnvironmentsEnvIdPlatformSecretsRoute
  '/dashboard/environments/$envId/platform/storage': typeof DashboardEnvironmentsEnvIdPlatformStorageRoute
  '/dashboard/environments/$envId/deployments/': typeof DashboardEnvironmentsEnvIdDeploymentsIndexRoute
  '/dashboard/environments/$envId/pods/': typeof DashboardEnvironmentsEnvIdPodsIndexRoute
  '/dashboard/environments/$envId/services/': typeof DashboardEnvironmentsEnvIdServicesIndexRoute
  '/dashboard/environments/$envId/pods/$namespace/$name': typeof DashboardEnvironmentsEnvIdPodsNamespaceNameRoute
  '/dashboard/environments/$envId/deployments/k8s/$namespace/$name': typeof DashboardEnvironmentsEnvIdDeploymentsK8sNamespaceNameRoute
  '/dashboard/environments/$envId/services/k8s/$namespace/$name': typeof DashboardEnvironmentsEnvIdServicesK8sNamespaceNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/access-requests': typeof DashboardAccessRequestsRoute
  '/dashboard/departments': typeof DashboardDepartmentsRoute
  '/dashboard/deployment-controls': typeof DashboardDeploymentControlsRoute
  '/dashboard/deployments': typeof DashboardDeploymentsRoute
  '/dashboard/no-access': typeof DashboardNoAccessRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/registries': typeof DashboardRegistriesRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/workspaces': typeof DashboardWorkspacesRoute
  '/environments/$envId': typeof EnvironmentsEnvIdRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/environments/$envId/integrations': typeof EnvironmentsEnvIdIntegrationsRoute
  '/dashboard/environments': typeof DashboardEnvironmentsIndexRoute
  '/dashboard/environments/$envId/containers': typeof DashboardEnvironmentsEnvIdContainersRoute
  '/dashboard/environments/$envId/integrations': typeof DashboardEnvironmentsEnvIdIntegrationsRoute
  '/dashboard/environments/$envId/logs': typeof DashboardEnvironmentsEnvIdLogsRoute
  '/dashboard/environments/$envId/metrics': typeof DashboardEnvironmentsEnvIdMetricsRoute
  '/dashboard/environments/$envId/platform': typeof DashboardEnvironmentsEnvIdPlatformRouteWithChildren
  '/dashboard/environments/$envId/policies': typeof DashboardEnvironmentsEnvIdPoliciesRoute
  '/dashboard/environments/$envId/registries': typeof DashboardEnvironmentsEnvIdRegistriesRoute
  '/dashboard/environments/$envId/runtime-events': typeof DashboardEnvironmentsEnvIdRuntimeEventsRoute
  '/dashboard/environments/$envId/secrets': typeof DashboardEnvironmentsEnvIdSecretsRoute
  '/dashboard/environments/$envId/service-catalog': typeof DashboardEnvironmentsEnvIdServiceCatalogRoute
  '/dashboard/environments/$envId/settings': typeof DashboardEnvironmentsEnvIdSettingsRoute
  '/dashboard/environments/$envId': typeof DashboardEnvironmentsEnvIdIndexRoute
  '/dashboard/environments/$envId/deployments/$jobId': typeof DashboardEnvironmentsEnvIdDeploymentsJobIdRoute
  '/dashboard/environments/$envId/platform/logs': typeof DashboardEnvironmentsEnvIdPlatformLogsRoute
  '/dashboard/environments/$envId/platform/networking': typeof DashboardEnvironmentsEnvIdPlatformNetworkingRoute
  '/dashboard/environments/$envId/platform/runtime': typeof DashboardEnvironmentsEnvIdPlatformRuntimeRoute
  '/dashboard/environments/$envId/platform/secrets': typeof DashboardEnvironmentsEnvIdPlatformSecretsRoute
  '/dashboard/environments/$envId/platform/storage': typeof DashboardEnvironmentsEnvIdPlatformStorageRoute
  '/dashboard/environments/$envId/deployments': typeof DashboardEnvironmentsEnvIdDeploymentsIndexRoute
  '/dashboard/environments/$envId/pods': typeof DashboardEnvironmentsEnvIdPodsIndexRoute
  '/dashboard/environments/$envId/services': typeof DashboardEnvironmentsEnvIdServicesIndexRoute
  '/dashboard/environments/$envId/pods/$namespace/$name': typeof DashboardEnvironmentsEnvIdPodsNamespaceNameRoute
  '/dashboard/environments/$envId/deployments/k8s/$namespace/$name': typeof DashboardEnvironmentsEnvIdDeploymentsK8sNamespaceNameRoute
  '/dashboard/environments/$envId/services/k8s/$namespace/$name': typeof DashboardEnvironmentsEnvIdServicesK8sNamespaceNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/access-requests': typeof DashboardAccessRequestsRoute
  '/dashboard/departments': typeof DashboardDepartmentsRoute
  '/dashboard/deployment-controls': typeof DashboardDeploymentControlsRoute
  '/dashboard/deployments': typeof DashboardDeploymentsRoute
  '/dashboard/environments': typeof DashboardEnvironmentsRouteWithChildren
  '/dashboard/no-access': typeof DashboardNoAccessRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/registries': typeof DashboardRegistriesRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/workspaces': typeof DashboardWorkspacesRoute
  '/environments/$envId': typeof EnvironmentsEnvIdRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/environments/$envId': typeof DashboardEnvironmentsEnvIdRouteWithChildren
  '/environments/$envId/integrations': typeof EnvironmentsEnvIdIntegrationsRoute
  '/dashboard/environments/': typeof DashboardEnvironmentsIndexRoute
  '/dashboard/environments/$envId/containers': typeof DashboardEnvironmentsEnvIdContainersRoute
  '/dashboard/environments/$envId/deployments': typeof DashboardEnvironmentsEnvIdDeploymentsRouteWithChildren
  '/dashboard/environments/$envId/integrations': typeof DashboardEnvironmentsEnvIdIntegrationsRoute
  '/dashboard/environments/$envId/logs': typeof DashboardEnvironmentsEnvIdLogsRoute
  '/dashboard/environments/$envId/metrics': typeof DashboardEnvironmentsEnvIdMetricsRoute
  '/dashboard/environments/$envId/platform': typeof DashboardEnvironmentsEnvIdPlatformRouteWithChildren
  '/dashboard/environments/$envId/pods': typeof DashboardEnvironmentsEnvIdPodsRouteWithChildren
  '/dashboard/environments/$envId/policies': typeof DashboardEnvironmentsEnvIdPoliciesRoute
  '/dashboard/environments/$envId/registries': typeof DashboardEnvironmentsEnvIdRegistriesRoute
  '/dashboard/environments/$envId/runtime-events': typeof DashboardEnvironmentsEnvIdRuntimeEventsRoute
  '/dashboard/environments/$envId/secrets': typeof DashboardEnvironmentsEnvIdSecretsRoute
  '/dashboard/environments/$envId/service-catalog': typeof DashboardEnvironmentsEnvIdServiceCatalogRoute
  '/dashboard/environments/$envId/services': typeof DashboardEnvironmentsEnvIdServicesRouteWithChildren
  '/dashboard/environments/$envId/settings': typeof DashboardEnvironmentsEnvIdSettingsRoute
  '/dashboard/environments/$envId/': typeof DashboardEnvironmentsEnvIdIndexRoute
  '/dashboard/environments/$envId/deployments/$jobId': typeof DashboardEnvironmentsEnvIdDeploymentsJobIdRoute
  '/dashboard/environments/$envId/platform/logs': typeof DashboardEnvironmentsEnvIdPlatformLogsRoute
  '/dashboard/environments/$envId/platform/networking': typeof DashboardEnvironmentsEnvIdPlatformNetworkingRoute
  '/dashboard/environments/$envId/platform/runtime': typeof DashboardEnvironmentsEnvIdPlatformRuntimeRoute
  '/dashboard/environments/$envId/platform/secrets': typeof DashboardEnvironmentsEnvIdPlatformSecretsRoute
  '/dashboard/environments/$envId/platform/storage': typeof DashboardEnvironmentsEnvIdPlatformStorageRoute
  '/dashboard/environments/$envId/deployments/': typeof DashboardEnvironmentsEnvIdDeploymentsIndexRoute
  '/dashboard/environments/$envId/pods/': typeof DashboardEnvironmentsEnvIdPodsIndexRoute
  '/dashboard/environments/$envId/services/': typeof DashboardEnvironmentsEnvIdServicesIndexRoute
  '/dashboard/environments/$envId/pods/$namespace/$name': typeof DashboardEnvironmentsEnvIdPodsNamespaceNameRoute
  '/dashboard/environments/$envId/deployments/k8s/$namespace/$name': typeof DashboardEnvironmentsEnvIdDeploymentsK8sNamespaceNameRoute
  '/dashboard/environments/$envId/services/k8s/$namespace/$name': typeof DashboardEnvironmentsEnvIdServicesK8sNamespaceNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/access-requests'
    | '/dashboard/departments'
    | '/dashboard/deployment-controls'
    | '/dashboard/deployments'
    | '/dashboard/environments'
    | '/dashboard/no-access'
    | '/dashboard/profile'
    | '/dashboard/registries'
    | '/dashboard/roles'
    | '/dashboard/services'
    | '/dashboard/teams'
    | '/dashboard/users'
    | '/dashboard/workspaces'
    | '/environments/$envId'
    | '/dashboard/'
    | '/dashboard/environments/$envId'
    | '/environments/$envId/integrations'
    | '/dashboard/environments/'
    | '/dashboard/environments/$envId/containers'
    | '/dashboard/environments/$envId/deployments'
    | '/dashboard/environments/$envId/integrations'
    | '/dashboard/environments/$envId/logs'
    | '/dashboard/environments/$envId/metrics'
    | '/dashboard/environments/$envId/platform'
    | '/dashboard/environments/$envId/pods'
    | '/dashboard/environments/$envId/policies'
    | '/dashboard/environments/$envId/registries'
    | '/dashboard/environments/$envId/runtime-events'
    | '/dashboard/environments/$envId/secrets'
    | '/dashboard/environments/$envId/service-catalog'
    | '/dashboard/environments/$envId/services'
    | '/dashboard/environments/$envId/settings'
    | '/dashboard/environments/$envId/'
    | '/dashboard/environments/$envId/deployments/$jobId'
    | '/dashboard/environments/$envId/platform/logs'
    | '/dashboard/environments/$envId/platform/networking'
    | '/dashboard/environments/$envId/platform/runtime'
    | '/dashboard/environments/$envId/platform/secrets'
    | '/dashboard/environments/$envId/platform/storage'
    | '/dashboard/environments/$envId/deployments/'
    | '/dashboard/environments/$envId/pods/'
    | '/dashboard/environments/$envId/services/'
    | '/dashboard/environments/$envId/pods/$namespace/$name'
    | '/dashboard/environments/$envId/deployments/k8s/$namespace/$name'
    | '/dashboard/environments/$envId/services/k8s/$namespace/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard/access-requests'
    | '/dashboard/departments'
    | '/dashboard/deployment-controls'
    | '/dashboard/deployments'
    | '/dashboard/no-access'
    | '/dashboard/profile'
    | '/dashboard/registries'
    | '/dashboard/roles'
    | '/dashboard/services'
    | '/dashboard/teams'
    | '/dashboard/users'
    | '/dashboard/workspaces'
    | '/environments/$envId'
    | '/dashboard'
    | '/environments/$envId/integrations'
    | '/dashboard/environments'
    | '/dashboard/environments/$envId/containers'
    | '/dashboard/environments/$envId/integrations'
    | '/dashboard/environments/$envId/logs'
    | '/dashboard/environments/$envId/metrics'
    | '/dashboard/environments/$envId/platform'
    | '/dashboard/environments/$envId/policies'
    | '/dashboard/environments/$envId/registries'
    | '/dashboard/environments/$envId/runtime-events'
    | '/dashboard/environments/$envId/secrets'
    | '/dashboard/environments/$envId/service-catalog'
    | '/dashboard/environments/$envId/settings'
    | '/dashboard/environments/$envId'
    | '/dashboard/environments/$envId/deployments/$jobId'
    | '/dashboard/environments/$envId/platform/logs'
    | '/dashboard/environments/$envId/platform/networking'
    | '/dashboard/environments/$envId/platform/runtime'
    | '/dashboard/environments/$envId/platform/secrets'
    | '/dashboard/environments/$envId/platform/storage'
    | '/dashboard/environments/$envId/deployments'
    | '/dashboard/environments/$envId/pods'
    | '/dashboard/environments/$envId/services'
    | '/dashboard/environments/$envId/pods/$namespace/$name'
    | '/dashboard/environments/$envId/deployments/k8s/$namespace/$name'
    | '/dashboard/environments/$envId/services/k8s/$namespace/$name'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/access-requests'
    | '/dashboard/departments'
    | '/dashboard/deployment-controls'
    | '/dashboard/deployments'
    | '/dashboard/environments'
    | '/dashboard/no-access'
    | '/dashboard/profile'
    | '/dashboard/registries'
    | '/dashboard/roles'
    | '/dashboard/services'
    | '/dashboard/teams'
    | '/dashboard/users'
    | '/dashboard/workspaces'
    | '/environments/$envId'
    | '/dashboard/'
    | '/dashboard/environments/$envId'
    | '/environments/$envId/integrations'
    | '/dashboard/environments/'
    | '/dashboard/environments/$envId/containers'
    | '/dashboard/environments/$envId/deployments'
    | '/dashboard/environments/$envId/integrations'
    | '/dashboard/environments/$envId/logs'
    | '/dashboard/environments/$envId/metrics'
    | '/dashboard/environments/$envId/platform'
    | '/dashboard/environments/$envId/pods'
    | '/dashboard/environments/$envId/policies'
    | '/dashboard/environments/$envId/registries'
    | '/dashboard/environments/$envId/runtime-events'
    | '/dashboard/environments/$envId/secrets'
    | '/dashboard/environments/$envId/service-catalog'
    | '/dashboard/environments/$envId/services'
    | '/dashboard/environments/$envId/settings'
    | '/dashboard/environments/$envId/'
    | '/dashboard/environments/$envId/deployments/$jobId'
    | '/dashboard/environments/$envId/platform/logs'
    | '/dashboard/environments/$envId/platform/networking'
    | '/dashboard/environments/$envId/platform/runtime'
    | '/dashboard/environments/$envId/platform/secrets'
    | '/dashboard/environments/$envId/platform/storage'
    | '/dashboard/environments/$envId/deployments/'
    | '/dashboard/environments/$envId/pods/'
    | '/dashboard/environments/$envId/services/'
    | '/dashboard/environments/$envId/pods/$namespace/$name'
    | '/dashboard/environments/$envId/deployments/k8s/$namespace/$name'
    | '/dashboard/environments/$envId/services/k8s/$namespace/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  EnvironmentsEnvIdRoute: typeof EnvironmentsEnvIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/environments/$envId': {
      id: '/environments/$envId'
      path: '/environments/$envId'
      fullPath: '/environments/$envId'
      preLoaderRoute: typeof EnvironmentsEnvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/workspaces': {
      id: '/dashboard/workspaces'
      path: '/workspaces'
      fullPath: '/dashboard/workspaces'
      preLoaderRoute: typeof DashboardWorkspacesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/teams': {
      id: '/dashboard/teams'
      path: '/teams'
      fullPath: '/dashboard/teams'
      preLoaderRoute: typeof DashboardTeamsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/roles': {
      id: '/dashboard/roles'
      path: '/roles'
      fullPath: '/dashboard/roles'
      preLoaderRoute: typeof DashboardRolesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/registries': {
      id: '/dashboard/registries'
      path: '/registries'
      fullPath: '/dashboard/registries'
      preLoaderRoute: typeof DashboardRegistriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/no-access': {
      id: '/dashboard/no-access'
      path: '/no-access'
      fullPath: '/dashboard/no-access'
      preLoaderRoute: typeof DashboardNoAccessRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/environments': {
      id: '/dashboard/environments'
      path: '/environments'
      fullPath: '/dashboard/environments'
      preLoaderRoute: typeof DashboardEnvironmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/deployments': {
      id: '/dashboard/deployments'
      path: '/deployments'
      fullPath: '/dashboard/deployments'
      preLoaderRoute: typeof DashboardDeploymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/deployment-controls': {
      id: '/dashboard/deployment-controls'
      path: '/deployment-controls'
      fullPath: '/dashboard/deployment-controls'
      preLoaderRoute: typeof DashboardDeploymentControlsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/departments': {
      id: '/dashboard/departments'
      path: '/departments'
      fullPath: '/dashboard/departments'
      preLoaderRoute: typeof DashboardDepartmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/access-requests': {
      id: '/dashboard/access-requests'
      path: '/access-requests'
      fullPath: '/dashboard/access-requests'
      preLoaderRoute: typeof DashboardAccessRequestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/environments/': {
      id: '/dashboard/environments/'
      path: '/'
      fullPath: '/dashboard/environments/'
      preLoaderRoute: typeof DashboardEnvironmentsIndexRouteImport
      parentRoute: typeof DashboardEnvironmentsRoute
    }
    '/environments/$envId/integrations': {
      id: '/environments/$envId/integrations'
      path: '/integrations'
      fullPath: '/environments/$envId/integrations'
      preLoaderRoute: typeof EnvironmentsEnvIdIntegrationsRouteImport
      parentRoute: typeof EnvironmentsEnvIdRoute
    }
    '/dashboard/environments/$envId': {
      id: '/dashboard/environments/$envId'
      path: '/$envId'
      fullPath: '/dashboard/environments/$envId'
      preLoaderRoute: typeof DashboardEnvironmentsEnvIdRouteImport
      parentRoute: typeof DashboardEnvironmentsRoute
    }
    '/dashboard/environments/$envId/': {
      id: '/dashboard/environments/$envId/'
      path: '/'
      fullPath: '/dashboard/environments/$envId/'
      preLoaderRoute: typeof DashboardEnvironmentsEnvIdIndexRouteImport
      parentRoute: typeof DashboardEnvironmentsEnvIdRoute
    }
    '/dashboard/environments/$envId/settings': {
      id: '/dashboard/environments/$envId/settings'
      path: '/settings'
      fullPath: '/dashboard/environments/$envId/settings'
      preLoaderRoute: typeof DashboardEnvironmentsEnvIdSettingsRouteImport
      parentRoute: typeof DashboardEnvironmentsEnvIdRoute
    }
    '/dashboard/environments/$envId/services': {
      id: '/dashboard/environments/$envId/services'
      path: '/services'
      fullPath: '/dashboard/environments/$envId/services'
      preLoaderRoute: typeof DashboardEnvironmentsEnvIdServicesRouteImport
      parentRoute: typeof DashboardEnvironmentsEnvIdRoute
    }
    '/dashboard/environments/$envId/service-catalog': {
      id: '/dashboard/environments/$envId/service-catalog'
      path: '/service-catalog'
      fullPath: '/dashboard/environments/$envId/service-catalog'
      preLoaderRoute: typeof DashboardEnvironmentsEnvIdServiceCatalogRouteImport
      parentRoute: typeof DashboardEnvironmentsEnvIdRoute
    }
    '/dashboard/environments/$envId/secrets': {
      id: '/dashboard/environments/$envId/secrets'
      path: '/secrets'
      fullPath: '/dashboard/environments/$envId/secrets'
      preLoaderRoute: typeof DashboardEnvironmentsEnvIdSecretsRouteImport
      parentRoute: typeof DashboardEnvironmentsEnvIdRoute
    }
    '/dashboard/environments/$envId/runtime-events': {
      id: '/dashboard/environments/$envId/runtime-events'
      path: '/runtime-events'
      fullPath: '/dashboard/environments/$envId/runtime-events'
      preLoaderRoute: typeof DashboardEnvironmentsEnvIdRuntimeEventsRouteImport
      parentRoute: typeof DashboardEnvironmentsEnvIdRoute
    }
    '/dashboard/environments/$envId/registries': {
      id: '/dashboard/environments/$envId/registries'
      path: '/registries'
      fullPath: '/dashboard/environments/$envId/registries'
      preLoaderRoute: typeof DashboardEnvironmentsEnvIdRegistriesRouteImport
      parentRoute: typeof DashboardEnvironmentsEnvIdRoute
    }
    '/dashboard/environments/$envId/policies': {
      id: '/dashboard/environments/$envId/policies'
      path: '/policies'
      fullPath: '/dashboard/environments/$envId/policies'
      preLoaderRoute: typeof DashboardEnvironmentsEnvIdPoliciesRouteImport
      parentRoute: typeof DashboardEnvironmentsEnvIdRoute
    }
    '/dashboard/environments/$envId/pods': {
      id: '/dashboard/environments/$envId/pods'
      path: '/pods'
      fullPath: '/dashboard/environments/$envId/pods'
      preLoaderRoute: typeof DashboardEnvironmentsEnvIdPodsRouteImport
      parentRoute: typeof DashboardEnvironmentsEnvIdRoute
    }
    '/dashboard/environments/$envId/platform': {
      id: '/dashboard/environments/$envId/platform'
      path: '/platform'
      fullPath: '/dashboard/environments/$envId/platform'
      preLoaderRoute: typeof DashboardEnvironmentsEnvIdPlatformRouteImport
      parentRoute: typeof DashboardEnvironmentsEnvIdRoute
    }
    '/dashboard/environments/$envId/metrics': {
      id: '/dashboard/environments/$envId/metrics'
      path: '/metrics'
      fullPath: '/dashboard/environments/$envId/metrics'
      preLoaderRoute: typeof DashboardEnvironmentsEnvIdMetricsRouteImport
      parentRoute: typeof DashboardEnvironmentsEnvIdRoute
    }
    '/dashboard/environments/$envId/logs': {
      id: '/dashboard/environments/$envId/logs'
      path: '/logs'
      fullPath: '/dashboard/environments/$envId/logs'
      preLoaderRoute: typeof DashboardEnvironmentsEnvIdLogsRouteImport
      parentRoute: typeof DashboardEnvironmentsEnvIdRoute
    }
    '/dashboard/environments/$envId/integrations': {
      id: '/dashboard/environments/$envId/integrations'
      path: '/integrations'
      fullPath: '/dashboard/environments/$envId/integrations'
      preLoaderRoute: typeof DashboardEnvironmentsEnvIdIntegrationsRouteImport
      parentRoute: typeof DashboardEnvironmentsEnvIdRoute
    }
    '/dashboard/environments/$envId/deployments': {
      id: '/dashboard/environments/$envId/deployments'
      path: '/deployments'
      fullPath: '/dashboard/environments/$envId/deployments'
      preLoaderRoute: typeof DashboardEnvironmentsEnvIdDeploymentsRouteImport
      parentRoute: typeof DashboardEnvironmentsEnvIdRoute
    }
    '/dashboard/environments/$envId/containers': {
      id: '/dashboard/environments/$envId/containers'
      path: '/containers'
      fullPath: '/dashboard/environments/$envId/containers'
      preLoaderRoute: typeof DashboardEnvironmentsEnvIdContainersRouteImport
      parentRoute: typeof DashboardEnvironmentsEnvIdRoute
    }
    '/dashboard/environments/$envId/services/': {
      id: '/dashboard/environments/$envId/services/'
      path: '/'
      fullPath: '/dashboard/environments/$envId/services/'
      preLoaderRoute: typeof DashboardEnvironmentsEnvIdServicesIndexRouteImport
      parentRoute: typeof DashboardEnvironmentsEnvIdServicesRoute
    }
    '/dashboard/environments/$envId/pods/': {
      id: '/dashboard/environments/$envId/pods/'
      path: '/'
      fullPath: '/dashboard/environments/$envId/pods/'
      preLoaderRoute: typeof DashboardEnvironmentsEnvIdPodsIndexRouteImport
      parentRoute: typeof DashboardEnvironmentsEnvIdPodsRoute
    }
    '/dashboard/environments/$envId/deployments/': {
      id: '/dashboard/environments/$envId/deployments/'
      path: '/'
      fullPath: '/dashboard/environments/$envId/deployments/'
      preLoaderRoute: typeof DashboardEnvironmentsEnvIdDeploymentsIndexRouteImport
      parentRoute: typeof DashboardEnvironmentsEnvIdDeploymentsRoute
    }
    '/dashboard/environments/$envId/platform/storage': {
      id: '/dashboard/environments/$envId/platform/storage'
      path: '/storage'
      fullPath: '/dashboard/environments/$envId/platform/storage'
      preLoaderRoute: typeof DashboardEnvironmentsEnvIdPlatformStorageRouteImport
      parentRoute: typeof DashboardEnvironmentsEnvIdPlatformRoute
    }
    '/dashboard/environments/$envId/platform/secrets': {
      id: '/dashboard/environments/$envId/platform/secrets'
      path: '/secrets'
      fullPath: '/dashboard/environments/$envId/platform/secrets'
      preLoaderRoute: typeof DashboardEnvironmentsEnvIdPlatformSecretsRouteImport
      parentRoute: typeof DashboardEnvironmentsEnvIdPlatformRoute
    }
    '/dashboard/environments/$envId/platform/runtime': {
      id: '/dashboard/environments/$envId/platform/runtime'
      path: '/runtime'
      fullPath: '/dashboard/environments/$envId/platform/runtime'
      preLoaderRoute: typeof DashboardEnvironmentsEnvIdPlatformRuntimeRouteImport
      parentRoute: typeof DashboardEnvironmentsEnvIdPlatformRoute
    }
    '/dashboard/environments/$envId/platform/networking': {
      id: '/dashboard/environments/$envId/platform/networking'
      path: '/networking'
      fullPath: '/dashboard/environments/$envId/platform/networking'
      preLoaderRoute: typeof DashboardEnvironmentsEnvIdPlatformNetworkingRouteImport
      parentRoute: typeof DashboardEnvironmentsEnvIdPlatformRoute
    }
    '/dashboard/environments/$envId/platform/logs': {
      id: '/dashboard/environments/$envId/platform/logs'
      path: '/logs'
      fullPath: '/dashboard/environments/$envId/platform/logs'
      preLoaderRoute: typeof DashboardEnvironmentsEnvIdPlatformLogsRouteImport
      parentRoute: typeof DashboardEnvironmentsEnvIdPlatformRoute
    }
    '/dashboard/environments/$envId/deployments/$jobId': {
      id: '/dashboard/environments/$envId/deployments/$jobId'
      path: '/$jobId'
      fullPath: '/dashboard/environments/$envId/deployments/$jobId'
      preLoaderRoute: typeof DashboardEnvironmentsEnvIdDeploymentsJobIdRouteImport
      parentRoute: typeof DashboardEnvironmentsEnvIdDeploymentsRoute
    }
    '/dashboard/environments/$envId/pods/$namespace/$name': {
      id: '/dashboard/environments/$envId/pods/$namespace/$name'
      path: '/$namespace/$name'
      fullPath: '/dashboard/environments/$envId/pods/$namespace/$name'
      preLoaderRoute: typeof DashboardEnvironmentsEnvIdPodsNamespaceNameRouteImport
      parentRoute: typeof DashboardEnvironmentsEnvIdPodsRoute
    }
    '/dashboard/environments/$envId/services/k8s/$namespace/$name': {
      id: '/dashboard/environments/$envId/services/k8s/$namespace/$name'
      path: '/k8s/$namespace/$name'
      fullPath: '/dashboard/environments/$envId/services/k8s/$namespace/$name'
      preLoaderRoute: typeof DashboardEnvironmentsEnvIdServicesK8sNamespaceNameRouteImport
      parentRoute: typeof DashboardEnvironmentsEnvIdServicesRoute
    }
    '/dashboard/environments/$envId/deployments/k8s/$namespace/$name': {
      id: '/dashboard/environments/$envId/deployments/k8s/$namespace/$name'
      path: '/k8s/$namespace/$name'
      fullPath: '/dashboard/environments/$envId/deployments/k8s/$namespace/$name'
      preLoaderRoute: typeof DashboardEnvironmentsEnvIdDeploymentsK8sNamespaceNameRouteImport
      parentRoute: typeof DashboardEnvironmentsEnvIdDeploymentsRoute
    }
  }
}

interface DashboardEnvironmentsEnvIdDeploymentsRouteChildren {
  DashboardEnvironmentsEnvIdDeploymentsJobIdRoute: typeof DashboardEnvironmentsEnvIdDeploymentsJobIdRoute
  DashboardEnvironmentsEnvIdDeploymentsIndexRoute: typeof DashboardEnvironmentsEnvIdDeploymentsIndexRoute
  DashboardEnvironmentsEnvIdDeploymentsK8sNamespaceNameRoute: typeof DashboardEnvironmentsEnvIdDeploymentsK8sNamespaceNameRoute
}

const DashboardEnvironmentsEnvIdDeploymentsRouteChildren: DashboardEnvironmentsEnvIdDeploymentsRouteChildren =
  {
    DashboardEnvironmentsEnvIdDeploymentsJobIdRoute:
      DashboardEnvironmentsEnvIdDeploymentsJobIdRoute,
    DashboardEnvironmentsEnvIdDeploymentsIndexRoute:
      DashboardEnvironmentsEnvIdDeploymentsIndexRoute,
    DashboardEnvironmentsEnvIdDeploymentsK8sNamespaceNameRoute:
      DashboardEnvironmentsEnvIdDeploymentsK8sNamespaceNameRoute,
  }

const DashboardEnvironmentsEnvIdDeploymentsRouteWithChildren =
  DashboardEnvironmentsEnvIdDeploymentsRoute._addFileChildren(
    DashboardEnvironmentsEnvIdDeploymentsRouteChildren,
  )

interface DashboardEnvironmentsEnvIdPlatformRouteChildren {
  DashboardEnvironmentsEnvIdPlatformLogsRoute: typeof DashboardEnvironmentsEnvIdPlatformLogsRoute
  DashboardEnvironmentsEnvIdPlatformNetworkingRoute: typeof DashboardEnvironmentsEnvIdPlatformNetworkingRoute
  DashboardEnvironmentsEnvIdPlatformRuntimeRoute: typeof DashboardEnvironmentsEnvIdPlatformRuntimeRoute
  DashboardEnvironmentsEnvIdPlatformSecretsRoute: typeof DashboardEnvironmentsEnvIdPlatformSecretsRoute
  DashboardEnvironmentsEnvIdPlatformStorageRoute: typeof DashboardEnvironmentsEnvIdPlatformStorageRoute
}

const DashboardEnvironmentsEnvIdPlatformRouteChildren: DashboardEnvironmentsEnvIdPlatformRouteChildren =
  {
    DashboardEnvironmentsEnvIdPlatformLogsRoute:
      DashboardEnvironmentsEnvIdPlatformLogsRoute,
    DashboardEnvironmentsEnvIdPlatformNetworkingRoute:
      DashboardEnvironmentsEnvIdPlatformNetworkingRoute,
    DashboardEnvironmentsEnvIdPlatformRuntimeRoute:
      DashboardEnvironmentsEnvIdPlatformRuntimeRoute,
    DashboardEnvironmentsEnvIdPlatformSecretsRoute:
      DashboardEnvironmentsEnvIdPlatformSecretsRoute,
    DashboardEnvironmentsEnvIdPlatformStorageRoute:
      DashboardEnvironmentsEnvIdPlatformStorageRoute,
  }

const DashboardEnvironmentsEnvIdPlatformRouteWithChildren =
  DashboardEnvironmentsEnvIdPlatformRoute._addFileChildren(
    DashboardEnvironmentsEnvIdPlatformRouteChildren,
  )

interface DashboardEnvironmentsEnvIdPodsRouteChildren {
  DashboardEnvironmentsEnvIdPodsIndexRoute: typeof DashboardEnvironmentsEnvIdPodsIndexRoute
  DashboardEnvironmentsEnvIdPodsNamespaceNameRoute: typeof DashboardEnvironmentsEnvIdPodsNamespaceNameRoute
}

const DashboardEnvironmentsEnvIdPodsRouteChildren: DashboardEnvironmentsEnvIdPodsRouteChildren =
  {
    DashboardEnvironmentsEnvIdPodsIndexRoute:
      DashboardEnvironmentsEnvIdPodsIndexRoute,
    DashboardEnvironmentsEnvIdPodsNamespaceNameRoute:
      DashboardEnvironmentsEnvIdPodsNamespaceNameRoute,
  }

const DashboardEnvironmentsEnvIdPodsRouteWithChildren =
  DashboardEnvironmentsEnvIdPodsRoute._addFileChildren(
    DashboardEnvironmentsEnvIdPodsRouteChildren,
  )

interface DashboardEnvironmentsEnvIdServicesRouteChildren {
  DashboardEnvironmentsEnvIdServicesIndexRoute: typeof DashboardEnvironmentsEnvIdServicesIndexRoute
  DashboardEnvironmentsEnvIdServicesK8sNamespaceNameRoute: typeof DashboardEnvironmentsEnvIdServicesK8sNamespaceNameRoute
}

const DashboardEnvironmentsEnvIdServicesRouteChildren: DashboardEnvironmentsEnvIdServicesRouteChildren =
  {
    DashboardEnvironmentsEnvIdServicesIndexRoute:
      DashboardEnvironmentsEnvIdServicesIndexRoute,
    DashboardEnvironmentsEnvIdServicesK8sNamespaceNameRoute:
      DashboardEnvironmentsEnvIdServicesK8sNamespaceNameRoute,
  }

const DashboardEnvironmentsEnvIdServicesRouteWithChildren =
  DashboardEnvironmentsEnvIdServicesRoute._addFileChildren(
    DashboardEnvironmentsEnvIdServicesRouteChildren,
  )

interface DashboardEnvironmentsEnvIdRouteChildren {
  DashboardEnvironmentsEnvIdContainersRoute: typeof DashboardEnvironmentsEnvIdContainersRoute
  DashboardEnvironmentsEnvIdDeploymentsRoute: typeof DashboardEnvironmentsEnvIdDeploymentsRouteWithChildren
  DashboardEnvironmentsEnvIdIntegrationsRoute: typeof DashboardEnvironmentsEnvIdIntegrationsRoute
  DashboardEnvironmentsEnvIdLogsRoute: typeof DashboardEnvironmentsEnvIdLogsRoute
  DashboardEnvironmentsEnvIdMetricsRoute: typeof DashboardEnvironmentsEnvIdMetricsRoute
  DashboardEnvironmentsEnvIdPlatformRoute: typeof DashboardEnvironmentsEnvIdPlatformRouteWithChildren
  DashboardEnvironmentsEnvIdPodsRoute: typeof DashboardEnvironmentsEnvIdPodsRouteWithChildren
  DashboardEnvironmentsEnvIdPoliciesRoute: typeof DashboardEnvironmentsEnvIdPoliciesRoute
  DashboardEnvironmentsEnvIdRegistriesRoute: typeof DashboardEnvironmentsEnvIdRegistriesRoute
  DashboardEnvironmentsEnvIdRuntimeEventsRoute: typeof DashboardEnvironmentsEnvIdRuntimeEventsRoute
  DashboardEnvironmentsEnvIdSecretsRoute: typeof DashboardEnvironmentsEnvIdSecretsRoute
  DashboardEnvironmentsEnvIdServiceCatalogRoute: typeof DashboardEnvironmentsEnvIdServiceCatalogRoute
  DashboardEnvironmentsEnvIdServicesRoute: typeof DashboardEnvironmentsEnvIdServicesRouteWithChildren
  DashboardEnvironmentsEnvIdSettingsRoute: typeof DashboardEnvironmentsEnvIdSettingsRoute
  DashboardEnvironmentsEnvIdIndexRoute: typeof DashboardEnvironmentsEnvIdIndexRoute
}

const DashboardEnvironmentsEnvIdRouteChildren: DashboardEnvironmentsEnvIdRouteChildren =
  {
    DashboardEnvironmentsEnvIdContainersRoute:
      DashboardEnvironmentsEnvIdContainersRoute,
    DashboardEnvironmentsEnvIdDeploymentsRoute:
      DashboardEnvironmentsEnvIdDeploymentsRouteWithChildren,
    DashboardEnvironmentsEnvIdIntegrationsRoute:
      DashboardEnvironmentsEnvIdIntegrationsRoute,
    DashboardEnvironmentsEnvIdLogsRoute: DashboardEnvironmentsEnvIdLogsRoute,
    DashboardEnvironmentsEnvIdMetricsRoute:
      DashboardEnvironmentsEnvIdMetricsRoute,
    DashboardEnvironmentsEnvIdPlatformRoute:
      DashboardEnvironmentsEnvIdPlatformRouteWithChildren,
    DashboardEnvironmentsEnvIdPodsRoute:
      DashboardEnvironmentsEnvIdPodsRouteWithChildren,
    DashboardEnvironmentsEnvIdPoliciesRoute:
      DashboardEnvironmentsEnvIdPoliciesRoute,
    DashboardEnvironmentsEnvIdRegistriesRoute:
      DashboardEnvironmentsEnvIdRegistriesRoute,
    DashboardEnvironmentsEnvIdRuntimeEventsRoute:
      DashboardEnvironmentsEnvIdRuntimeEventsRoute,
    DashboardEnvironmentsEnvIdSecretsRoute:
      DashboardEnvironmentsEnvIdSecretsRoute,
    DashboardEnvironmentsEnvIdServiceCatalogRoute:
      DashboardEnvironmentsEnvIdServiceCatalogRoute,
    DashboardEnvironmentsEnvIdServicesRoute:
      DashboardEnvironmentsEnvIdServicesRouteWithChildren,
    DashboardEnvironmentsEnvIdSettingsRoute:
      DashboardEnvironmentsEnvIdSettingsRoute,
    DashboardEnvironmentsEnvIdIndexRoute: DashboardEnvironmentsEnvIdIndexRoute,
  }

const DashboardEnvironmentsEnvIdRouteWithChildren =
  DashboardEnvironmentsEnvIdRoute._addFileChildren(
    DashboardEnvironmentsEnvIdRouteChildren,
  )

interface DashboardEnvironmentsRouteChildren {
  DashboardEnvironmentsEnvIdRoute: typeof DashboardEnvironmentsEnvIdRouteWithChildren
  DashboardEnvironmentsIndexRoute: typeof DashboardEnvironmentsIndexRoute
}

const DashboardEnvironmentsRouteChildren: DashboardEnvironmentsRouteChildren = {
  DashboardEnvironmentsEnvIdRoute: DashboardEnvironmentsEnvIdRouteWithChildren,
  DashboardEnvironmentsIndexRoute: DashboardEnvironmentsIndexRoute,
}

const DashboardEnvironmentsRouteWithChildren =
  DashboardEnvironmentsRoute._addFileChildren(
    DashboardEnvironmentsRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardAccessRequestsRoute: typeof DashboardAccessRequestsRoute
  DashboardDepartmentsRoute: typeof DashboardDepartmentsRoute
  DashboardDeploymentControlsRoute: typeof DashboardDeploymentControlsRoute
  DashboardDeploymentsRoute: typeof DashboardDeploymentsRoute
  DashboardEnvironmentsRoute: typeof DashboardEnvironmentsRouteWithChildren
  DashboardNoAccessRoute: typeof DashboardNoAccessRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardRegistriesRoute: typeof DashboardRegistriesRoute
  DashboardRolesRoute: typeof DashboardRolesRoute
  DashboardServicesRoute: typeof DashboardServicesRoute
  DashboardTeamsRoute: typeof DashboardTeamsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardWorkspacesRoute: typeof DashboardWorkspacesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccessRequestsRoute: DashboardAccessRequestsRoute,
  DashboardDepartmentsRoute: DashboardDepartmentsRoute,
  DashboardDeploymentControlsRoute: DashboardDeploymentControlsRoute,
  DashboardDeploymentsRoute: DashboardDeploymentsRoute,
  DashboardEnvironmentsRoute: DashboardEnvironmentsRouteWithChildren,
  DashboardNoAccessRoute: DashboardNoAccessRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardRegistriesRoute: DashboardRegistriesRoute,
  DashboardRolesRoute: DashboardRolesRoute,
  DashboardServicesRoute: DashboardServicesRoute,
  DashboardTeamsRoute: DashboardTeamsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardWorkspacesRoute: DashboardWorkspacesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface EnvironmentsEnvIdRouteChildren {
  EnvironmentsEnvIdIntegrationsRoute: typeof EnvironmentsEnvIdIntegrationsRoute
}

const EnvironmentsEnvIdRouteChildren: EnvironmentsEnvIdRouteChildren = {
  EnvironmentsEnvIdIntegrationsRoute: EnvironmentsEnvIdIntegrationsRoute,
}

const EnvironmentsEnvIdRouteWithChildren =
  EnvironmentsEnvIdRoute._addFileChildren(EnvironmentsEnvIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  EnvironmentsEnvIdRoute: EnvironmentsEnvIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
