package seeds

import (
	"github.com/google/uuid"
	"github.com/kusumaningrat/ternakclouds/internal/servicecatalog"
)

var Applications = []servicecatalog.CatalogItem{
	{
		ID:                   uuid.MustParse("00000010-0000-0000-0001-000000000001"),
		Name:                 "custom-app",
		DisplayName:          "Custom Application",
		Description:          "Deploy any containerised application with a custom image",
		Category:             "Application",
		DefaultImage:         "",
		DefaultContainerPort: 8080,
		DefaultCPU:           200,
		DefaultMemory:        256,
		HealthCheckType:      "http",
		HealthCheckPath:      "/health",
		IsPublicImage:        true,
	},
	{
		ID:                   uuid.MustParse("00000010-0000-0000-0001-000000000002"),
		Name:                 "nodejs-api",
		DisplayName:          "NodeJS API",
		Description:          "Node.js HTTP API server (Express / Fastify)",
		Category:             "Application",
		DefaultImage:         "node:20-alpine",
		DefaultContainerPort: 3000,
		DefaultCPU:           200,
		DefaultMemory:        256,
		HealthCheckType:      "http",
		HealthCheckPath:      "/health",
		IsPublicImage:        true,
	},
	{
		ID:                   uuid.MustParse("00000010-0000-0000-0001-000000000003"),
		Name:                 "nextjs",
		DisplayName:          "Next.js",
		Description:          "React framework for full-stack web applications",
		Category:             "Application",
		DefaultImage:         "node:20-alpine",
		DefaultContainerPort: 3000,
		DefaultCPU:           300,
		DefaultMemory:        512,
		HealthCheckType:      "http",
		HealthCheckPath:      "/",
		IsPublicImage:        true,
	},
	{
		ID:                   uuid.MustParse("00000010-0000-0000-0001-000000000004"),
		Name:                 "go-api",
		DisplayName:          "Go API",
		Description:          "High-performance Go HTTP service",
		Category:             "Application",
		DefaultImage:         "golang:1.22-alpine",
		DefaultContainerPort: 8080,
		DefaultCPU:           100,
		DefaultMemory:        128,
		HealthCheckType:      "http",
		HealthCheckPath:      "/health",
		IsPublicImage:        true,
	},
	{
		ID:                   uuid.MustParse("00000010-0000-0000-0001-000000000005"),
		Name:                 "python-fastapi",
		DisplayName:          "Python FastAPI",
		Description:          "Modern, fast Python web API framework",
		Category:             "Application",
		DefaultImage:         "python:3.12-slim",
		DefaultContainerPort: 8000,
		DefaultCPU:           200,
		DefaultMemory:        256,
		HealthCheckType:      "http",
		HealthCheckPath:      "/health",
		IsPublicImage:        true,
	},
}
