// Jenkinsfile — {{.ServiceName}} (Nomad deploy)
// Generated by TernakClouds IDP

pipeline {
  agent any

  environment {
    SERVICE_NAME    = '{{.ServiceName}}'
    REGISTRY        = '{{if .RegistryEndpoint}}{{.RegistryEndpoint}}{{else}}registry.hub.docker.com{{end}}'
    IMAGE_PATH      = '{{if .ImagePath}}{{.ImagePath}}{{else}}{{.ServiceName}}{{end}}'
    BRANCH          = '{{.Branch}}'
    NOMAD_NAMESPACE = '{{.Namespace}}'
  }

  stages {
    stage('Build & Push') {
      when { branch env.BRANCH }
      steps {
        script {
          def imageTag = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
          docker.withRegistry("https://${env.REGISTRY}", 'registry-credentials') {
            def img = docker.build("${env.REGISTRY}/${env.IMAGE_PATH}:${imageTag}")
            img.push()
            img.push('latest')
            env.IMAGE_TAG = imageTag
          }
        }
      }
    }

    stage('Deploy to {{.EnvironmentLabel}} via Nomad') {
      when { branch env.BRANCH }
      environment {
        NOMAD_ADDR  = credentials('nomad-addr')
        NOMAD_TOKEN = credentials('nomad-token')
      }
      steps {
        sh """
          curl -fsSL https://releases.hashicorp.com/nomad/1.8.4/nomad_1.8.4_linux_amd64.zip -o nomad.zip
          unzip -o nomad.zip && chmod +x nomad

          ./nomad job run \\
            -var="image=${env.REGISTRY}/${env.IMAGE_PATH}:${env.IMAGE_TAG}" \\
            -namespace="${env.NOMAD_NAMESPACE}" \\
            {{.ServiceName}}.nomad.hcl
        """
      }
    }
  }

  post {
    failure {
      echo 'Nomad deployment failed for {{.ServiceName}} on {{.EnvironmentLabel}}'
    }
  }
}
