// Jenkinsfile — {{.ServiceName}} (SSH deploy)
// Generated by TernakClouds IDP

pipeline {
  agent any

  environment {
    SERVICE_NAME = '{{.ServiceName}}'
    REGISTRY     = '{{if .RegistryEndpoint}}{{.RegistryEndpoint}}{{else}}registry.hub.docker.com{{end}}'
    IMAGE_PATH   = '{{if .ImagePath}}{{.ImagePath}}{{else}}{{.ServiceName}}{{end}}'
    BRANCH       = '{{.Branch}}'
  }

  stages {
    stage('Build & Push') {
      when { branch env.BRANCH }
      steps {
        script {
          def imageTag = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
          docker.withRegistry("https://${env.REGISTRY}", 'registry-credentials') {
            def img = docker.build("${env.REGISTRY}/${env.IMAGE_PATH}:${imageTag}")
            img.push()
            img.push('latest')
            env.IMAGE_TAG = imageTag
          }
        }
      }
    }

    stage('Deploy to {{.EnvironmentLabel}} via SSH') {
      when { branch env.BRANCH }
      steps {
        sshagent(credentials: ['ssh-deploy-key']) {
          withCredentials([
            string(credentialsId: 'ssh-host', variable: 'SSH_HOST'),
            string(credentialsId: 'ssh-user', variable: 'SSH_USER'),
          ]) {
            sh """
              ssh -o StrictHostKeyChecking=no \${SSH_USER}@\${SSH_HOST} "
                cd /opt/services/{{.ServiceName}}
                IMAGE_TAG=${env.IMAGE_TAG} docker compose pull
                IMAGE_TAG=${env.IMAGE_TAG} docker compose up -d --remove-orphans
                docker image prune -f"
            """
          }
        }
      }
    }
  }

  post {
    failure {
      echo 'SSH deployment failed for {{.ServiceName}} on {{.EnvironmentLabel}}'
    }
  }
}
