// Jenkinsfile — {{.ServiceName}}
// Generated by TernakClouds IDP

pipeline {
  agent any

  environment {
    SERVICE_NAME = '{{.ServiceName}}'
    REGISTRY     = '{{if .RegistryEndpoint}}{{.RegistryEndpoint}}{{else}}registry.hub.docker.com{{end}}'
    IMAGE_PATH   = '{{if .ImagePath}}{{.ImagePath}}{{else}}{{.ServiceName}}{{end}}'
    BRANCH       = '{{.Branch}}'
  }

  stages {
    stage('Build & Push') {
      when { branch env.BRANCH }
      steps {
        script {
          def imageTag = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
          docker.withRegistry("https://${env.REGISTRY}", 'registry-credentials') {
            def img = docker.build("${env.REGISTRY}/${env.IMAGE_PATH}:${imageTag}")
            img.push()
            img.push('latest')
            env.IMAGE_TAG = imageTag
          }
        }
      }
    }

    stage('Deploy to {{.EnvironmentLabel}}') {
      when { branch env.BRANCH }
      environment {
        TERNAK_IDP_URL   = credentials('ternak-idp-url')
        TERNAK_IDP_TOKEN = credentials('ternak-idp-token')
        TERNAK_WORKSPACE = credentials('ternak-workspace')
      }
      steps {
        sh """
          curl -X POST "\${TERNAK_IDP_URL}/api/v1/workspaces/\${TERNAK_WORKSPACE}/environments/{{.EnvironmentLabel}}/platform-apps/${SERVICE_NAME}/redeploy" \\
            -H "Authorization: Bearer \${TERNAK_IDP_TOKEN}" \\
            -H "Content-Type: application/json" \\
            -d "{\\"image_tag\\":\\"${env.IMAGE_TAG}\\"}"
        """
      }
    }
  }

  post {
    failure {
      echo 'Pipeline failed for {{.ServiceName}} on environment {{.EnvironmentLabel}}'
    }
  }
}
