// Jenkinsfile — {{.ServiceName}} (Helm deploy)
// Generated by TernakClouds IDP

pipeline {
  agent any

  environment {
    SERVICE_NAME  = '{{.ServiceName}}'
    REGISTRY      = '{{if .RegistryEndpoint}}{{.RegistryEndpoint}}{{else}}registry.hub.docker.com{{end}}'
    IMAGE_PATH    = '{{if .ImagePath}}{{.ImagePath}}{{else}}{{.ServiceName}}{{end}}'
    BRANCH        = '{{.Branch}}'
    K8S_NAMESPACE = '{{.K8sNamespace}}'
  }

  stages {
    stage('Build & Push') {
      when { branch env.BRANCH }
      steps {
        script {
          def imageTag = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
          docker.withRegistry("https://${env.REGISTRY}", 'registry-credentials') {
            def img = docker.build("${env.REGISTRY}/${env.IMAGE_PATH}:${imageTag}")
            img.push()
            img.push('latest')
            env.IMAGE_TAG = imageTag
          }
        }
      }
    }

    stage('Deploy to {{.EnvironmentLabel}} via Helm') {
      when { branch env.BRANCH }
      steps {
        withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG')]) {
          sh """
            helm upgrade --install {{.ServiceName}} ./chart \\
              --namespace ${env.K8S_NAMESPACE} \\
              --create-namespace \\
              --set image.repository=${env.REGISTRY}/${env.IMAGE_PATH} \\
              --set image.tag=${env.IMAGE_TAG} \\
              --set environment={{.EnvironmentLabel}} \\
              --wait --timeout 120s \\
              --atomic
          """
        }
      }
    }
  }

  post {
    failure {
      echo 'Helm deployment failed for {{.ServiceName}} on {{.EnvironmentLabel}}'
    }
  }
}
