// Jenkinsfile — {{.ServiceName}} (kubectl deploy)
// Generated by TernakClouds IDP

pipeline {
  agent any

  environment {
    SERVICE_NAME  = '{{.ServiceName}}'
    REGISTRY      = '{{if .RegistryEndpoint}}{{.RegistryEndpoint}}{{else}}registry.hub.docker.com{{end}}'
    IMAGE_PATH    = '{{if .ImagePath}}{{.ImagePath}}{{else}}{{.ServiceName}}{{end}}'
    BRANCH        = '{{.Branch}}'
    K8S_NAMESPACE = '{{.K8sNamespace}}'
  }

  stages {
    stage('Build & Push') {
      when { branch env.BRANCH }
      steps {
        script {
          def imageTag = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
          docker.withRegistry("https://${env.REGISTRY}", 'registry-credentials') {
            def img = docker.build("${env.REGISTRY}/${env.IMAGE_PATH}:${imageTag}")
            img.push()
            img.push('latest')
            env.IMAGE_TAG = imageTag
          }
        }
      }
    }

    stage('Deploy to {{.EnvironmentLabel}} via kubectl') {
      when { branch env.BRANCH }
      steps {
        withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG')]) {
          sh """
            kubectl set image deployment/{{.ServiceName}} \\
              {{.ServiceName}}=${env.REGISTRY}/${env.IMAGE_PATH}:${env.IMAGE_TAG} \\
              --namespace ${env.K8S_NAMESPACE}

            kubectl rollout status deployment/{{.ServiceName}} \\
              --namespace ${env.K8S_NAMESPACE} --timeout=120s
          """
        }
      }
    }
  }

  post {
    failure {
      echo 'kubectl deployment failed for {{.ServiceName}} on {{.EnvironmentLabel}}'
    }
  }
}
